
locale                : "en-GB"
remote_theme          : "mmistakes/minimal-mistakes@4.26.1"
minimal_mistakes_skin : "mint"
plugins:
  - jekyll-feed
  - jekyll-include-cache

title                 : "yhg.io"
description           : "The personal website of YH Gan."
baseurl               : "" 
url                   : "https://yhg.io" 
email                 : "gan@yhg.io"
twitter:
  username            : "yhgan"
repository            : "ganyinghung"
author:
  name                : "Ying Hung GAN"
  bio                 : "Someone"
  location            : "Reading, UK"

enable_copy_code_button  : true

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: false
      show_date: true
      read_time: true
      share: false




